### ISSUE TITLE
error message when docker compose up qwc-services qwc-solr

### ISSUE THREAD

**Issue by kahermann** [qwc-services/qwc-fulltext-search-service#4]
the pull request for the solr 8.4.1 image was released within the command:
administrator@administrator-HP-ProBook-6560b:/qwc-services/qwc-docker$ sudo docker-compose up qwc-fulltext-search-service

administrator@administrator-HP-ProBook-6560b:/qwc-services/qwc-docker$ sudo docker-compose up qwc-solr
[sudo] Passwort für administrator: 
Creating network "qwc-docker_default" with the default driver
Creating qwc-docker_qwc-postgis_1 ... done
Creating qwc-docker_qwc-solr_1    ... done
Attaching to qwc-docker_qwc-solr_1
qwc-solr_1                     | Executing /opt/docker-solr/scripts/solr-precreate gdi /gdi_conf
qwc-solr_1                     | Copying solr.xml
qwc-solr_1                     | cp: cannot create regular file '/var/solr/data/solr.xml': Permission denied
qwc-docker_qwc-solr_1 exited with code 1

**Comment by pka** [comment]
You probably have to execute the command

```
sudo chown 8983:8983 volumes/solr/data
```

once before starting the container.

**Comment by kahermann** [comment]
Hi Pirmin,


changed user and group with

sudo chown 8983:8983 volumes/solr/data

started qwc-full-text-search container

Started Solr Administration User Interface: http://localhost:8983/solr/

Please see the error message and the log beyond

Thanks for your efforts

Karl

administrator@administrator-HP-ProBook-6560b:/qwc-services/qwc-docker$ sudo docker-compose up qwc-fulltext-search-service
Creating network "qwc-docker_default" with the default driver
Creating qwc-docker_qwc-postgis_1 ... done
Creating qwc-docker_qwc-solr_1    ... done
Creating qwc-docker_qwc-fulltext-search-service_1 ... done
Attaching to qwc-docker_qwc-fulltext-search-service_1
qwc-fulltext-search-service_1  | *** Starting uWSGI 2.0.17.1 (64bit) on [Tue Dec  8 18:52:31 2020] ***
qwc-fulltext-search-service_1  | compiled with version: 8.2.0 on 17 December 2018 15:55:40
qwc-fulltext-search-service_1  | os: Linux-5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020
qwc-fulltext-search-service_1  | nodename: a4bfa8032fe5
qwc-fulltext-search-service_1  | machine: x86_64
qwc-fulltext-search-service_1  | clock source: unix
qwc-fulltext-search-service_1  | pcre jit disabled
qwc-fulltext-search-service_1  | detected number of CPU cores: 4
qwc-fulltext-search-service_1  | current working directory: /
qwc-fulltext-search-service_1  | detected binary path: /usr/sbin/uwsgi
qwc-fulltext-search-service_1  | setgid() to 102
qwc-fulltext-search-service_1  | setuid() to 101
qwc-fulltext-search-service_1  | chdir() to /srv/qwc_service
qwc-fulltext-search-service_1  | your memory page size is 4096 bytes
qwc-fulltext-search-service_1  | detected max file descriptor number: 1048576
qwc-fulltext-search-service_1  | lock engine: pthread robust mutexes
qwc-fulltext-search-service_1  | thunder lock: disabled (you can enable it with --thunder-lock)
qwc-fulltext-search-service_1  | uwsgi socket 0 bound to TCP address :9090 fd 3
qwc-fulltext-search-service_1  | Python version: 3.6.9 (default, Jul 19 2020, 03:46:11)  [GCC 8.3.0]
qwc-fulltext-search-service_1  | Python main interpreter initialized at 0x55ee471e1100
qwc-fulltext-search-service_1  | python threads support enabled
qwc-fulltext-search-service_1  | your server socket listen backlog is limited to 100 connections
qwc-fulltext-search-service_1  | your mercy for graceful operations on workers is 60 seconds
qwc-fulltext-search-service_1  | mapped 274112 bytes (267 KB) for 4 cores
qwc-fulltext-search-service_1  | *** Operational MODE: threaded ***
qwc-fulltext-search-service_1  | mounting server:app on /api/v2/search
qwc-fulltext-search-service_1  | WSGI app 0 (mountpoint='/api/v2/search') ready in 1 seconds on interpreter 0x55ee471e1100 pid: 1 (default app)
qwc-fulltext-search-service_1  | *** uWSGI is running in multiple interpreter mode ***
qwc-fulltext-search-service_1  | spawned uWSGI master process (pid: 1)qwc-fulltext-search-service_1  | spawned uWSGI worker 1 (pid: 6, cores: 4)

Started Solr Administration User Interface: http://localhost:8983/solr/

the error message appears

SolrCore Initialization Failures

    {{core}}: {{error}}

Please check your logs for more information

{{exception.msg}}

the docker-compose logs -f shows

administrator@administrator-HP-ProBook-6560b:/qwc-services/qwc-docker$ sudo docker-compose logs -f
Attaching to qwc-docker_qwc-fulltext-search-service_1, qwc-docker_qwc-solr_1, qwc-docker_qwc-postgis_1
qwc-solr_1                     | Executing /opt/docker-solr/scripts/solr-precreate gdi /gdi_conf
qwc-solr_1                     | Executing /opt/docker-solr/scripts/precreate-core gdi /gdi_conf
qwc-solr_1                     | Core gdi already exists
qwc-solr_1                     | Starting Solr
qwc-solr_1                     | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
qwc-solr_1                     | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
qwc-solr_1                     | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
qwc-solr_1                     | 2020-12-08 18:52:32.334 INFO  (main) [   ] o.e.j.u.log Logging initialized @1739ms to org.eclipse.jetty.util.log.Slf4jLog
qwc-solr_1                     | 2020-12-08 18:52:32.591 WARN  (main) [   ] o.e.j.s.AbstractConnector Ignoring deprecated socket close linger time
qwc-solr_1                     | 2020-12-08 18:52:32.591 WARN  (main) [   ] o.e.j.x.XmlConfiguration Deprecated method public void org.eclipse.jetty.server.ServerConnector.setSoLingerTime(int) in file:///opt/solr-8.4.1/server/etc/jetty-http.xml
qwc-solr_1                     | 2020-12-08 18:52:32.604 INFO  (main) [   ] o.e.j.s.Server jetty-9.4.19.v20190610; built: 2019-06-10T16:30:51.723Z; git: afcf563148970e98786327af5e07c261fda175d3; jvm 11.0.9.1+1
qwc-solr_1                     | 2020-12-08 18:52:32.678 INFO  (main) [   ] o.e.j.d.p.ScanningAppProvider Deployment monitor [file:///opt/solr-8.4.1/server/contexts/] at interval 0
qwc-solr_1                     | 2020-12-08 18:52:33.168 INFO  (main) [   ] o.e.j.w.StandardDescriptorProcessor NO JSP Support for /solr, did not find org.apache.jasper.servlet.JspServlet
qwc-solr_1                     | 2020-12-08 18:52:33.183 INFO  (main) [   ] o.e.j.s.session DefaultSessionIdManager workerName=node0
qwc-solr_1                     | 2020-12-08 18:52:33.183 INFO  (main) [   ] o.e.j.s.session No SessionScavenger set, using defaults
qwc-solr_1                     | 2020-12-08 18:52:33.186 INFO  (main) [   ] o.e.j.s.session node0 Scavenging every 660000ms
qwc-solr_1                     | 2020-12-08 18:52:33.342 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter Using logger factory org.apache.logging.slf4j.Log4jLoggerFactory
qwc-solr_1                     | 2020-12-08 18:52:33.347 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter  ___      _       Welcome to Apache Solr™ version 8.4.1
qwc-solr_1                     | 2020-12-08 18:52:33.348 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter / __| ___| |_ _   Starting in standalone mode on port 8983
qwc-solr_1                     | 2020-12-08 18:52:33.348 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter \__ \/ _ \ | '_|  Install dir: /opt/solr
qwc-solr_1                     | 2020-12-08 18:52:33.348 INFO  (main) [   ] o.a.s.s.SolrDispatchFilter |___/\___/_|_|    Start time: 2020-12-08T18:52:33.348617Z
qwc-solr_1                     | 2020-12-08 18:52:33.424 INFO  (main) [   ] o.a.s.c.SolrResourceLoader Using system property solr.solr.home: /var/solr/data
qwc-solr_1                     | 2020-12-08 18:52:33.434 INFO  (main) [   ] o.a.s.c.SolrXmlConfig Loading container configuration from /var/solr/data/solr.xml
qwc-solr_1                     | 2020-12-08 18:52:33.542 INFO  (main) [   ] o.a.s.c.SolrXmlConfig MBean server found: com.sun.jmx.mbeanserver.JmxMBeanServer@5b7a8434, but no JMX reporters were configured - adding default JMX reporter.
qwc-solr_1                     | 2020-12-08 18:52:34.347 INFO  (main) [   ] o.a.s.h.c.HttpShardHandlerFactory Host whitelist initialized: WhitelistHostChecker [whitelistHosts=null, whitelistHostCheckingEnabled=true]
qwc-solr_1                     | 2020-12-08 18:52:34.572 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@618ad2aa[provider=null,keyStore=null,trustStore=null]
qwc-solr_1                     | 2020-12-08 18:52:34.572 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@618ad2aa[provider=null,keyStore=null,trustStore=null]
qwc-solr_1                     | 2020-12-08 18:52:34.814 WARN  (main) [   ] o.e.j.u.s.S.config Trusting all certificates configured for Client@146dcfe6[provider=null,keyStore=null,trustStore=null]
qwc-solr_1                     | 2020-12-08 18:52:34.815 WARN  (main) [   ] o.e.j.u.s.S.config No Client EndPointIdentificationAlgorithm configured for Client@146dcfe6[provider=null,keyStore=null,trustStore=null]
qwc-solr_1                     | 2020-12-08 18:52:34.846 WARN  (main) [   ] o.a.s.c.CoreContainer Not all security plugins configured!  authentication=disabled authorization=disabled.  Solr is only as secure as you make it. Consider configuring authentication/authorization before exposing Solr to users internal or external.  See https://s.apache.org/solrsecurity for more info
qwc-solr_1                     | 2020-12-08 18:52:35.102 INFO  (main) [   ] o.a.s.c.TransientSolrCoreCacheDefault Allocating transient cache for 2147483647 transient cores
qwc-solr_1                     | 2020-12-08 18:52:35.106 INFO  (main) [   ] o.a.s.h.a.MetricsHistoryHandler No .system collection, keeping metrics history in memory.
qwc-solr_1                     | 2020-12-08 18:52:35.216 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.node' (registry 'solr.node') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@5b7a8434
qwc-solr_1                     | 2020-12-08 18:52:35.217 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jvm' (registry 'solr.jvm') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@5b7a8434
qwc-solr_1                     | 2020-12-08 18:52:35.225 INFO  (main) [   ] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.jetty' (registry 'solr.jetty') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@5b7a8434
qwc-solr_1                     | 2020-12-08 18:52:35.267 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Found 1 core definitions underneath /var/solr/data
qwc-solr_1                     | 2020-12-08 18:52:35.268 INFO  (main) [   ] o.a.s.c.CorePropertiesLocator Cores are: [gdi]
qwc-solr_1                     | 2020-12-08 18:52:35.386 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.c.SolrResourceLoader [gdi] Added 62 libs to classloader, from paths: [/opt/solr/contrib/clustering/lib, /opt/solr/contrib/extraction/lib, /opt/solr/contrib/langid/lib, /opt/solr/contrib/velocity/lib, /opt/solr/dist, /var/solr/data/gdi/conf/lib]
qwc-solr_1                     | 2020-12-08 18:52:35.397 INFO  (main) [   ] o.e.j.s.h.ContextHandler Started o.e.j.w.WebAppContext@379ab47b{/solr,file:///opt/solr-8.4.1/server/solr-webapp/webapp/,AVAILABLE}{/opt/solr-8.4.1/server/solr-webapp/webapp}
qwc-solr_1                     | 2020-12-08 18:52:35.411 INFO  (main) [   ] o.e.j.s.AbstractConnector Started ServerConnector@7894f09b{HTTP/1.1,[http/1.1, h2c]}{0.0.0.0:8983}
qwc-solr_1                     | 2020-12-08 18:52:35.411 INFO  (main) [   ] o.e.j.s.Server Started @4823ms
qwc-solr_1                     | 2020-12-08 18:52:35.665 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.c.SolrConfig Using Lucene MatchVersion: 7.7.1
qwc-solr_1                     | 2020-12-08 18:52:35.923 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.s.IndexSchema [gdi] Schema name=default-config
qwc-solr_1                     | 2020-12-08 18:52:36.714 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.s.IndexSchema Loaded schema default-config/1.6 with uniqueid field id
qwc-solr_1                     | 2020-12-08 18:52:36.746 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.c.CoreContainer Creating SolrCore 'gdi' using configuration from instancedir /var/solr/data/gdi, trusted=true
qwc-solr_1                     | 2020-12-08 18:52:36.783 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.m.r.SolrJmxReporter JMX monitoring for 'solr.core.gdi' (registry 'solr.core.gdi') enabled at server: com.sun.jmx.mbeanserver.JmxMBeanServer@5b7a8434
qwc-solr_1                     | 2020-12-08 18:52:36.804 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.c.SolrCore [[gdi] ] Opening new SolrCore at [/var/solr/data/gdi], dataDir=[/var/solr/data/gdi/data/]
qwc-solr_1                     | 2020-12-08 18:52:36.854 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.r.XSLTResponseWriter xsltCacheLifetimeSeconds=5
qwc-solr_1                     | 2020-12-08 18:52:37.554 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.u.UpdateHandler Using UpdateLog implementation: org.apache.solr.update.UpdateLog
qwc-solr_1                     | 2020-12-08 18:52:37.554 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.u.UpdateLog Initializing UpdateLog: dataDir= defaultSyncLevel=FLUSH numRecordsToKeep=100 maxNumLogsToKeep=10 numVersionBuckets=65536
qwc-fulltext-search-service_1  | *** Starting uWSGI 2.0.17.1 (64bit) on [Tue Dec  8 18:52:31 2020] ***
qwc-fulltext-search-service_1  | compiled with version: 8.2.0 on 17 December 2018 15:55:40
qwc-fulltext-search-service_1  | os: Linux-5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020
qwc-fulltext-search-service_1  | nodename: a4bfa8032fe5
qwc-fulltext-search-service_1  | machine: x86_64
qwc-fulltext-search-service_1  | clock source: unix
qwc-fulltext-search-service_1  | pcre jit disabled
qwc-fulltext-search-service_1  | detected number of CPU cores: 4
qwc-fulltext-search-service_1  | current working directory: /
qwc-fulltext-search-service_1  | detected binary path: /usr/sbin/uwsgi
qwc-fulltext-search-service_1  | setgid() to 102
qwc-fulltext-search-service_1  | setuid() to 101
qwc-fulltext-search-service_1  | chdir() to /srv/qwc_service
qwc-fulltext-search-service_1  | your memory page size is 4096 bytes
qwc-fulltext-search-service_1  | detected max file descriptor number: 1048576
qwc-fulltext-search-service_1  | lock engine: pthread robust mutexes
qwc-fulltext-search-service_1  | thunder lock: disabled (you can enable it with --thunder-lock)
qwc-fulltext-search-service_1  | uwsgi socket 0 bound to TCP address :9090 fd 3
qwc-fulltext-search-service_1  | Python version: 3.6.9 (default, Jul 19 2020, 03:46:11)  [GCC 8.3.0]
qwc-fulltext-search-service_1  | Python main interpreter initialized at 0x55ee471e1100
qwc-fulltext-search-service_1  | python threads support enabled
qwc-fulltext-search-service_1  | your server socket listen backlog is limited to 100 connections
qwc-fulltext-search-service_1  | your mercy for graceful operations on workers is 60 seconds
qwc-fulltext-search-service_1  | mapped 274112 bytes (267 KB) for 4 cores
qwc-fulltext-search-service_1  | *** Operational MODE: threaded ***
qwc-fulltext-search-service_1  | mounting server:app on /api/v2/search
qwc-fulltext-search-service_1  | WSGI app 0 (mountpoint='/api/v2/search') ready in 1 seconds on interpreter 0x55ee471e1100 pid: 1 (default app)
qwc-fulltext-search-service_1  | *** uWSGI is running in multiple interpreter mode ***
qwc-fulltext-search-service_1  | spawned uWSGI master process (pid: 1)
qwc-fulltext-search-service_1  | spawned uWSGI worker 1 (pid: 6, cores: 4)
qwc-solr_1                     | 2020-12-08 18:52:37.572 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.u.CommitTracker Hard AutoCommit: if uncommitted for 15000ms;
qwc-solr_1                     | 2020-12-08 18:52:37.572 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.u.CommitTracker Soft AutoCommit: disabled
qwc-solr_1                     | 2020-12-08 18:52:37.663 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.s.SolrIndexSearcher Opening [Searcher@609b7971[gdi] main]
qwc-solr_1                     | 2020-12-08 18:52:37.677 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.r.ManagedResourceStorage File-based storage initialized to use dir: /var/solr/data/gdi/conf
qwc-solr_1                     | 2020-12-08 18:52:37.714 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.h.c.SpellCheckComponent Initializing spell checkers
qwc-solr_1                     | 2020-12-08 18:52:37.728 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.s.DirectSolrSpellChecker init: {name=default,field=_text_,classname=solr.DirectSolrSpellChecker,distanceMeasure=internal,accuracy=0.5,maxEdits=2,minPrefix=1,maxInspections=5,minQueryLength=4,maxQueryFrequency=0.01}
qwc-solr_1                     | 2020-12-08 18:52:37.749 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.h.ReplicationHandler Commits will be reserved for 10000ms.
qwc-solr_1                     | 2020-12-08 18:52:37.765 INFO  (coreLoadExecutor-9-thread-1) [   x:gdi] o.a.s.u.UpdateLog Could not find max version in index or recent updates, using new clock 1685537221786992640
qwc-solr_1                     | 2020-12-08 18:52:37.780 INFO  (searcherExecutor-10-thread-1-processing-x:gdi) [   x:gdi] o.a.s.c.QuerySenderListener QuerySenderListener sending requests to Searcher@609b7971[gdi] main{ExitableDirectoryReader(UninvertingDirectoryReader())}
qwc-solr_1                     | 2020-12-08 18:52:37.780 INFO  (searcherExecutor-10-thread-1-processing-x:gdi) [   x:gdi] o.a.s.c.QuerySenderListener QuerySenderListener done.
qwc-solr_1                     | 2020-12-08 18:52:37.780 INFO  (searcherExecutor-10-thread-1-processing-x:gdi) [   x:gdi] o.a.s.h.c.SpellCheckComponent Loading spell index for spellchecker: default
qwc-solr_1                     | 2020-12-08 18:52:37.798 INFO  (searcherExecutor-10-thread-1-processing-x:gdi) [   x:gdi] o.a.s.c.SolrCore [gdi] Registered new searcher Searcher@609b7971[gdi] main{ExitableDirectoryReader(UninvertingDirectoryReader())}
qwc-postgis_1                  | LOG:  database system was shut down at 2020-11-19 12:01:26 UTC
qwc-postgis_1                  | LOG:  MultiXact member wraparound protections are now enabled
qwc-postgis_1                  | LOG:  autovacuum launcher started
qwc-postgis_1                  | LOG:  database system is ready to accept connections
dddddd








________________________________
Von: Pirmin Kalberer <notifications@github.com>
Gesendet: Dienstag, 8. Dezember 2020 17:17:34
An: qwc-services/qwc-fulltext-search-service
Cc: Hermann Karl; Author
Betreff: Re: [qwc-services/qwc-fulltext-search-service] error message when docker compose up qwc-services qwc-solr (#4)


You probably have to execute the command

sudo chown 8983:8983 volumes/solr/data


once before starting the container.
